
#include <algorithm>
#include <assert.h>
#include <boost/foreach.hpp>
#include <boost/format.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/make_shared.hpp>
#include <boost/math/common_factor_rt.hpp>
#include <boost/pointer_cast.hpp>
#include <boost/scoped_array.hpp>
#include <boost/shared_ptr.hpp>
#include <boost/tuple/tuple.hpp>
#include <cassert>
#include <cctype>
#include <cmath>
#include <cstddef>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <exception>
#include <fcntl.h>
#include <fstream>
#include <functional>
#include <iomanip>
#include <ios>
#include <iostream>
#include <iterator>
#include <limits>
#include <list>
#include <map>
#include <math.h>
#include <memory>
#include <numeric>
#include <openddlparser/OpenDDLParser.h>
#include <ostream>
#include <set>
#include <sstream>
#include <stack>
#include <stdarg.h>
#include <stddef.h>
#include <stdexcept>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <vector>

#include <assimp/DefaultLogger.hpp>
#include <assimp/Exporter.hpp>
#include <assimp/IOSystem.hpp>
#include <assimp/Importer.hpp>
#include <assimp/LogStream.hpp>
#include <assimp/ai_assert.h>
#include <assimp/cimport.h>
#include <assimp/importerdesc.h>
#include <assimp/material.h>
#include <assimp/postprocess.h>
#include <assimp/scene.h>
#include <assimp/version.h>

//#include <irrXML.h>
//#include <openddlparser/DDLNode.h>
//#include <openddlparser/OpenDDLCommon.h>
//#include <openddlparser/OpenDDLExport.h>
//#include <openddlparser/OpenDDLParser.h>
//#include <openddlparser/Value.h>
//#include <sys/param.h>

//#include "assimp/IOStream.hpp"
//#include "assimp/Logger.hpp"
//#include "assimp/NullLogger.hpp"
//#include "assimp/ProgressHandler.hpp"
//#include "assimp/anim.h"
//#include "assimp/camera.h"
//#include "assimp/cexport.h"
//#include "assimp/cfileio.h"
//#include "assimp/color4.h"
//#include "assimp/config.h"
//#include "assimp/defs.h"
//#include "assimp/light.h"
//#include "assimp/matrix3x3.h"
//#include "assimp/matrix4x4.h"
//#include "assimp/mesh.h"
//#include "assimp/metadata.h"
//#include "assimp/quaternion.h"
//#include "assimp/texture.h"
//#include "assimp/types.h"
//#include "assimp/vector2.h"
//#include "assimp/vector3.h"
//
//#include "../code/3DSExporter.h"
//#include "../code/3DSHelper.h"
//#include "../code/3DSLoader.h"
//#include "../code/ACLoader.h"
//#include "../code/ASELoader.h"
//#include "../code/ASEParser.h"
//#include "../code/AssbinExporter.h"
//#include "../code/AssbinLoader.h"
//#include "../code/assbin_chunks.h"
//#include "../code/AssxmlExporter.h"
//#include "../code/B3DImporter.h"
//#include "../code/BaseImporter.h"
//#include "../code/BaseProcess.h"
//#include "../code/Bitmap.h"
//#include "../code/BlenderBMesh.h"
//#include "../code/BlenderDNA.h"
//#include "../code/BlenderIntermediate.h"
//#include "../code/BlenderLoader.h"
//#include "../code/BlenderModifier.h"
//#include "../code/BlenderScene.h"
//#include "../code/BlenderSceneGen.h"
//#include "../code/BlenderTessellator.h"
//#include "../code/BlobIOSystem.h"
//#include "../code/BVHLoader.h"
//#include "../code/ByteSwapper.h"
//#include "../code/C4DImporter.h"
//#include "../code/CalcTangentsProcess.h"
//#include "../code/CInterfaceIOWrapper.h"
//#include "../code/COBLoader.h"
//#include "../code/COBScene.h"
//#include "../code/ColladaExporter.h"
//#include "../code/ColladaHelper.h"
//#include "../code/ColladaLoader.h"
//#include "../code/ColladaParser.h"
//#include "../code/ComputeUVMappingProcess.h"
//#include "../code/ConvertToLHProcess.h"
//#include "../code/CSMLoader.h"
//#include "../code/DeboneProcess.h"
//#include "../code/DefaultIOStream.h"
//#include "../code/DefaultIOSystem.h"
//#include "../code/DefaultProgressHandler.h"
//#include "../code/Defines.h"
//#include "../code/DXFHelper.h"
//#include "../code/DXFLoader.h"
//#include "../code/Exceptional.h"
//#include "../code/fast_atof.h"
//#include "../code/FBXCompileConfig.h"
//#include "../code/FBXConverter.h"
//#include "../code/FBXDocument.h"
//#include "../code/FBXDocumentUtil.h"
//#include "../code/FBXImporter.h"
//#include "../code/FBXImportSettings.h"
//#include "../code/FBXMeshGeometry.h"
//#include "../code/FBXParser.h"
//#include "../code/FBXProperties.h"
//#include "../code/FBXTokenizer.h"
//#include "../code/FBXUtil.h"
//#include "../code/FileLogStream.h"
//#include "../code/FileSystemFilter.h"
//#include "../code/FindDegenerates.h"
//#include "../code/FindInstancesProcess.h"
//#include "../code/FindInvalidDataProcess.h"
//#include "../code/FixNormalsStep.h"
//#include "../code/GenericProperty.h"
//#include "../code/GenFaceNormalsProcess.h"
//#include "../code/GenVertexNormalsProcess.h"
//#include "../code/glTFAsset.h"
//#include "../code/glTFAssetWriter.h"
//#include "../code/glTFExporter.h"
//#include "../code/glTFImporter.h"
//#include "../code/HalfLifeFileData.h"
//#include "../code/Hash.h"
//#include "../code/HMPFileData.h"
//#include "../code/HMPLoader.h"
//#include "../code/IFCLoader.h"
//#include "../code/IFCReaderGen.h"
//#include "../code/IFCUtil.h"
//#include "../code/IFF.h"
//#include "../code/Importer.h"
//#include "../code/ImproveCacheLocality.h"
//#include "../code/IRRLoader.h"
//#include "../code/IRRMeshLoader.h"
//#include "../code/IRRShared.h"
//#include "../code/irrXMLWrapper.h"
//#include "../code/JoinVerticesProcess.h"
//#include "../code/LimitBoneWeightsProcess.h"
//#include "../code/LineSplitter.h"
//#include "../code/LogAux.h"
//#include "../code/LWOAnimation.h"
//#include "../code/LWOFileData.h"
//#include "../code/LWOLoader.h"
//#include "../code/LWSLoader.h"
//#include "../code/Macros.h"
//#include "../code/MakeVerboseFormat.h"
//#include "../code/MaterialSystem.h"
//#include "../code/MD2FileData.h"
//#include "../code/MD2Loader.h"
//#include "../code/MD2NormalTable.h"
//#include "../code/MD3FileData.h"
//#include "../code/MD3Loader.h"
//#include "../code/MD4FileData.h"
//#include "../code/MD5Loader.h"
//#include "../code/MD5Parser.h"
//#include "../code/MDCFileData.h"
//#include "../code/MDCLoader.h"
//#include "../code/MDCNormalTable.h"
//#include "../code/MDLDefaultColorMap.h"
//#include "../code/MDLFileData.h"
//#include "../code/MDLLoader.h"
//#include "../code/MemoryIOWrapper.h"
//#include "../code/MS3DLoader.h"
//#include "../code/NDOLoader.h"
//#include "../code/NFFLoader.h"
//#include "../code/ObjExporter.h"
//#include "../code/ObjFileData.h"
//#include "../code/ObjFileImporter.h"
//#include "../code/ObjFileMtlImporter.h"
//#include "../code/ObjFileParser.h"
//#include "../code/ObjTools.h"
//#include "../code/OFFLoader.h"
//#include "../code/OgreBinarySerializer.h"
//#include "../code/OgreImporter.h"
//#include "../code/OgreParsingUtils.h"
//#include "../code/OgreStructs.h"
//#include "../code/OgreXmlSerializer.h"
//#include "../code/OpenGEXExporter.h"
//#include "../code/OpenGEXImporter.h"
//#include "../code/OpenGEXStructs.h"
//#include "../code/OptimizeGraph.h"
//#include "../code/OptimizeMeshes.h"
//#include "../code/ParsingUtils.h"
//#include "../code/PlyExporter.h"
//#include "../code/PlyLoader.h"
//#include "../code/PlyParser.h"
//#include "../code/PolyTools.h"
//#include "../code/PretransformVertices.h"
//#include "../code/ProcessHelper.h"
//#include "../code/Profiler.h"
//#include "../code/Q3BSPFileData.h"
//#include "../code/Q3BSPFileImporter.h"
//#include "../code/Q3BSPFileParser.h"
//#include "../code/Q3BSPZipArchive.h"
//#include "../code/Q3DLoader.h"
//#include "../code/qnan.h"
//#include "../code/RawLoader.h"
//#include "../code/RemoveComments.h"
//#include "../code/RemoveRedundantMaterials.h"
//#include "../code/RemoveVCProcess.h"
//#include "../code/SceneCombiner.h"
//#include "../code/ScenePreprocessor.h"
//#include "../code/ScenePrivate.h"
//#include "../code/SGSpatialSort.h"
//#include "../code/SIBImporter.h"
//#include "../code/SkeletonMeshBuilder.h"
//#include "../code/SMDLoader.h"
//#include "../code/SmoothingGroups.h"
//#include "../code/SortByPTypeProcess.h"
//#include "../code/SpatialSort.h"
//#include "../code/SplitByBoneCountProcess.h"
//#include "../code/SplitLargeMeshes.h"
//#include "../code/StandardShapes.h"
//#include "../code/StdOStreamLogStream.h"
//#include "../code/StepExporter.h"
//#include "../code/STEPFile.h"
//#include "../code/STEPFileEncoding.h"
//#include "../code/STEPFileReader.h"
//#include "../code/STLExporter.h"
//#include "../code/STLLoader.h"
//#include "../code/StreamReader.h"
//#include "../code/StreamWriter.h"
//#include "../code/StringComparison.h"
//#include "../code/StringUtils.h"
//#include "../code/Subdivision.h"
//#include "../code/TargetAnimation.h"
//#include "../code/TerragenLoader.h"
//#include "../code/TextureTransform.h"
//#include "../code/TinyFormatter.h"
//#include "../code/TriangulateProcess.h"
//#include "../code/UnrealLoader.h"
//#include "../code/ValidateDataStructure.h"
//#include "../code/Vertex.h"
//#include "../code/VertexTriangleAdjacency.h"
//#include "../code/Win32DebugLogStream.h"
//#include "../code/XFileExporter.h"
//#include "../code/XFileHelper.h"
//#include "../code/XFileImporter.h"
//#include "../code/XFileParser.h"
//#include "../code/XGLLoader.h"
//#include "../code/XMLTools.h"
